### ISSUE TITLE
Legend is not shown in bar graph when the first value is 0

### ISSUE THREAD

**Issue by hakimio** [goat1000/SVGGraph#10]
It might be fine to skip legend entry when **all** values are 0 or null, but I really don't understand why it hides legend when only the first value is zero.

[Yes, I know that I can set "legend_show_empty" to "true".]

**Comment by goat1000** [comment]
This sounds like a bug, but I don't have enough information to be able to reproduce it. Could you supply me with an example that demonstrates the bug?

**Comment by hakimio** [comment]
Simply try to generate bar graph (only 2D and 3D bar graphs have this issue) with values set to "[0, 1, 2, 3, 4, 5]" and  "legend_entries" set to "['Series1']". I would expect to see the legend show up in the resulting graph, but it will not be drawn.
If you take a look at BarGraph->Draw() method, you should be able to see why this is the case.

**Comment by goat1000** [comment]
Are you expecting to see an empty legend? You only have one entry in your `legend_entries` and that maps to the `0` value. If you want the legend to show an entry for each dataset/series instead of each data item you must use a multi-dataset graph type or change the `legend_type` option to `"dataset"`.

**Comment by hakimio** [comment]
I see. I didn't know that I have to set "legend_type" to "dataset".
