### ISSUE TITLE
Issues and inconsistencies with "label_space" setting

### ISSUE THREAD

**Issue by hakimio** [goat1000/SVGGraph#12]
I tried adding some labels to axis and found some inconsistent behavior of "label_space" setting. Some of the issues I describe here could be just attributed to inconsistent design but I still think they should be at least discussed.
1) Unlike "axis_text_space", "label_space" creates padding on both sides of labels. I believe outer padding should only be controlled using "pad_left"/"pad_right" settings and "label_space" should only offset axis labels from axis division text or axis themselves.
2) Unlike "axis_text_space", there is no way to separately control horizontal and vertical axis label padding (not so important, but still worth mentioning).
3) The space between axis labels and axis division text of the same axis (ie vertical) is influenced by the size of axis division text on another axis (ie horizontal). For example, vertical axis label spacing is influenced by horizontal axis division text. As I understand, this because axis labels are offset from the whole bounding box of the graph instead of just axis division text. This creates some weird looking results:
* Dual Y axis line graph with 5px axis label spacing:
![dual y axis line graph](https://cloud.githubusercontent.com/assets/768105/24609014/51d2453a-1879-11e7-8967-a15cc4ba6e2b.PNG)

* Dual Y axis bar graph with 10px axis label spacing:
![dual y axis bar graph](https://cloud.githubusercontent.com/assets/768105/24609058/835f863a-1879-11e7-8533-3a694c35b37a.PNG)

As you can see, "Clicks" axis label in line graph is offset more from right vertical axis division text even "label_spacing" is only 5px, when it's 10px for bar graph and it's offset less, because the horizontal axis division text in the line graph is sticking out significantly more than in the bar graph.
Would be really nice if axis labels would be offset only from division text instead of the whole bounding box. How difficult would it be to achieve that?

**Comment by goat1000** [comment]
The way the labels are spaced and positioned is very simple at the moment.

If there is a label:
- the padding is increased by (number of lines in label * *label_font_size*) + (2 * *label_space*)
- the label is drawn *label_space* pixels from the new padding position border, centred within the padding region

Positioning for the scale text on the axes is a lot more complicated, so I don't really want to add the labels into those calculations if I can help it.

Would it be easier to use custom labels for the axes instead?

**Comment by hakimio** [comment]
Basically, the main issues I have are two:
* Setting "label_space" not only offsets the label from axis division text, but also creates additional unwanted padding outside of the graph.
To solve this issue I tried the following "fix", but I am not really sure if that's really the way to go:
https://github.com/hakimio/SVGGraph/commit/92d2c7aa7d1822fe14fd5cb50706d61b3db2e955

* If you take a look at the line graph image I posted, you should be able to see that the "Clicks" axis label is offset a lot from division text, even "label_space" is set to only 5px. While on the other side of the graph, "Impressions" axis label has relatively very little padding.

I am not really sure what you mean when you say "custom" labels.

**Comment by goat1000** [comment]
For your first point, I agree that is it is a bit inconsistent - but it has been that way for five years now, so changing it might surprise people a bit. I don't mind adding new options to add more control, but I don't like changing what existing options do.

The spacing between the labels and the text being different left and right looks likely to be down to incorrect measurements (in this particular case). You could try changing the *axis_font_adjust* options to see if they help: [axis_font_adjust](http://www.goat1000.com/svggraph-docs/axis_font_adjust).

Custom labels are added to the graph using the *label* option, and can go anywhere: [custom labels](http://www.goat1000.com/svggraph-custom-labels.php)

**Comment by hakimio** [comment]
If you release a new major version, it's ok to break existing functionality.
Thanks, I will try that option and let you know if it helps.

Sorry, but no, I don't want to add labels using absolute positioning because the space taken by division text varies a lot and I want axis labels to be positioned relative to division text.

**Comment by hakimio** [comment]
Also, just a simple question: are axis labels offset from the green rectangle or the red one:
![bounding box](https://cloud.githubusercontent.com/assets/768105/24626127/901c5e02-18b0-11e7-9912-bc331797c084.png)
As far as I understood, it's the red rectangle - bounding box of the whole graph, instead of just vertical axis division text. This would explain the inconsistency between the way bar graph and line graph axis labels are positioned.

**Comment by goat1000** [comment]
Yes, if SVGGraph gets its measurements right then the labels are offset from the red box.

**Comment by hakimio** [comment]
How difficult would it be to modify the code to offset from the green box? If you don't think the current inconsistency is an issue and don't want to change the behavior for everyone, maybe you could give some suggestions how I could modify my version to achieve it?

**Comment by goat1000** [comment]
That would be a little bit tricky. You would need to measure the bounding boxes of the text on each axis, then position the label making sure it didn't overlap them. (Obviously "Clicks" wouldn't overlap the text on the X-axis here, but a longer label or on a smaller graph it might.)

So the `LabelAdjustment` function would need to change to reflect the different position of the label and the space it makes, and the `FindAxisTextBBox` function to find the bounding boxes of each axis' text. The bounding box of the label would have to be measured somewhere as well, so that would really require a new `_adjust` option for a better guess at the text width.

**Comment by hakimio** [comment]
Ok, then one more question: is there a way to create inner padding, so that the first and last values on the horizontal axis would be offset inwards?

**Comment by goat1000** [comment]
That is on the to-do list, but it is another thing that turned out to be more complicated than I thought it would be.

Here are a few other options that you could use as work-arounds, in order of how obvious the side-effects are:
- use [axis_font_adjust_v](http://www.goat1000.com/svggraph-docs/axis_font_adjust_v) to increase the width measurements for the Y-axis text
- use [axis_text_callback_y](http://www.goat1000.com/svggraph-docs/axis_text_callback_y) to add space characters to the Y-axis text, increasing their measurements
- use [axis_text_space_v](http://www.goat1000.com/svggraph-docs/axis_text_space_v) to increase the space between the Y-axis and the text
- use [axis_font_size_h](http://www.goat1000.com/svggraph-docs/axis_font_size_h) to reduce the font size of the X-axis labels
- use [axis_text_angle_h](http://www.goat1000.com/svggraph-docs/axis_text_angle_h) to rotate the text on the X-axis

**Comment by hakimio** [comment]
Thanks for suggesting possible workarounds. I think, I'll just adapt one of them for now.
Feel free to close this bug report, if you don't think any of the issues mentioned here is something you should look at.
