### ISSUE TITLE
Fix the width of axis space

### ISSUE THREAD

**Issue by roarkmccolgan** [goat1000/SVGGraph#24]
Hi! 

Thanks for the great work on this library.
I have an issue where I would like to display a second graph below the first to make them look like the same graph.

![image](https://user-images.githubusercontent.com/1567162/57450833-d86d1d80-725f-11e9-8784-df7706647cc3.png)

The axis text is different for each so I would like to "fix" the space on the left so the graphs align perfectly.

_Obviously a better solution would be to use one graph but I can't work out how to use a single data set and have different colours and axis values show up like "Overall Performance" and "Your Result"
If you could help with that that would be awesome._

Thanks!

**Comment by goat1000** [comment]
You can do this using two graphs by setting the `grid_left` and `grid_right` options to fix the positions of the two ends of the grid, you just have to leave enough space for the text. You can use a negative value for `grid_right` to set it as a distance from the right of the graph document instead of the left.

To do it as a single graph, you would have to use something like this:
```PHP
$settings = [
  'structure' => [
    'key' => 0, 'value' => [1, 2, 3],
    'colour' => 'colour1',
  ],
  // more settings...
];

$values = [
  ['Your Result', 58, 'colour1' => '#949'],
  ['Overall Performance', 33, 33, 33],
];

$graph = new Goat1000\SVGGraph\SVGGraph(700, 150, $settings);
$graph->colours(['#99a', '#667', '#334']);
$graph->values($values);
```

This uses the standard colour array to set the colours of the three "Overall Performance" bars, and the `colour1` entry from the `$values` array to set the "Your Result" bar colour.

**Comment by roarkmccolgan** [comment]
You are a legend thank you!
