### ISSUE TITLE
image instead of text for Y axis

### ISSUE THREAD

**Issue by crozet-magenta** [goat1000/SVGGraph#25]
Hi,
I'm using your lib to create graph representing satisfaction of customers. In my form I use smileys to get the customer feedback and those smileys are translated into integers in the database. Then, I would like to reuse them in the graph instead of numbers. Is there a way to use images instead of text for the values of the y axis ?

Here is what i'm trying to achieve :
![graph](https://user-images.githubusercontent.com/6060274/57915291-bc393400-7890-11e9-9734-e8845a4f2e2c.png)

**Comment by goat1000** [comment]
There are a couple of ways you could do that - the easiest is to use a callback to replace the number with a character entity:

```PHP
$settings = [
  // ... more settings here ...
  // emojis are quite hard to make out in smaller font sizes
  'axis_font_size_v' => 24,
  'axis_text_callback_x' => function($k, $v) {
    $smileys = [
      "&#x1f621;",
      "&#x1f641;",
      "&#x1f610;",
      "&#x1f642;",
      "&#x1f600;",
      "&#x1f601;",
    ];
    return isset($smileys[$k]) ? $smileys[$k] : '';
  },
];
```

These options set a callback for the X-axis, which is the vertical one on a horizontal bar graph. The `isset()` is required because SVGGraph can measure more values than are actually displayed on the graph.

I've just picked some random emojis to go in the example, but I don't think they match the ones you are using. The full list is here: https://unicode.org/emoji/charts/full-emoji-list.html

The other way to do it is using the `shape` option and images, but that is a bit more complicated.

**Comment by crozet-magenta** [comment]
nice thank you, I missed that in the doc :)
I used the shape option because I need to use an image and not an unicode emoji

**Comment by goat1000** [comment]
The reference for using shapes and images is on this page: https://www.goat1000.com/svggraph-shapes.php

**Comment by goat1000** [comment]
I'm not sure what you are trying to do, but it sounds complicated and I don't know if you can do it using shapes.

**Comment by goat1000** [comment]
There is no provision in SVGGraph for positioning images with text at the moment. It would be possible, but quite a lot of work.

Unfortunately text in SVG doesn't flow around things the way it does in HTML, so there is no easy way to do it.
