### ISSUE TITLE
Wrong colors when pie chart contains 0 size pieces.

### ISSUE THREAD

**Issue by SamMousa** [goat1000/SVGGraph#4]
Suppose I have a pie chart with 3 slices: R G and B.
I've configured colors for the chart as follows:
````
$colors = ['#FF0000', '#00FF00', '#0000FF'];
````
Now when I draw the chart with values: `200, 100, 50`, it will correctly use the colors i've provided.
If instead I draw the chart with values `0, 0, 200` then instead of using the 3rd color it uses the first color in the array.

**Comment by goat1000** [comment]
This is the expected behaviour - it works this way to prevent adjacent slices being the same colour. If you need to set specific colours for items of data, using structured data is the best way to achieve it.

As an alternative I could add an option for pie graphs to use the specific colours from the array, though I wouldn't want to enable it by default.

**Comment by SamMousa** [comment]
Okay; i'll do some research and close this if structured data is a sufficient solution!

Thanks for the quick response.
