### ISSUE TITLE
Predictable colors

### ISSUE THREAD

**Issue by boussou** [goat1000/SVGGraph#7]
Hi,
In SVGGraphPieGraph.php in function Draw():

from line 123:

```
      if($this->legend_show_empty || $item->value != 0) {
        $attr = array('fill' => $this->GetColour($item, $slice_no, NULL, true,
          true));
        $this->SetStroke($attr, $item, 0, 'round');

        // use the original position for legend index
        $this->SetLegendEntry(0, $original_position, $item, $attr);
        ++$slice;
      }
```

IMHO there is a gotcha that could be easily avoided.
I needed predictable colors, and the call to $this->GetColour uses $slice: **I think it should be $slice_no.**

Imagine the following data:

```
     [success] => 3            Green
    [half] => 0                Yellow
    [failed] => 7              Red
```

current behavior:
Since the value for **"half"** is 0, it is skipped, and as a consequence the next value take **"Yellow"** for "failed" because $slice is 1 (the current drawn slice) while $slice_no point the proper data.

**Comment by goat1000** [comment]
I have been asked about this a few times - usually I just say "use structured data to set the specific colours instead", but maybe it is time I added an option to do the pie graph colours by original position. The `$slice_no` value changes depending on whether the `"sort"` option is enabled, so `$original_position` is the value to use to index directly into the `$colours` array.

I don't want to make this the default behaviour though, because I think the way it works now is easier to understand when the colours are not quite right than with the colour set by position, for example:

```
  $colours = array('red', 'green', 'blue');
  $values = array(10, 0, 0, 20, 0, 40, 0);
```

With the current behaviour there will always be a red, green and blue slice. Using the original position instead would mean two red slices and a blue one.

**Comment by boussou** [comment]
I understand: There is no universal & proper way of selecting colors. 

if we rephrase the problem, IMHO it is "what to do with 0 values?".
Maybe a callback for 0 values would be useful here, or  externalize the "Color picker policy" in a extendable user defined class or anonymous function. 

or extend your current logic to keep memory of the last selected color and avoiding repeating it on consecutive slices?

(On my side, problem solded as I patched my version of SVGGraph).
Thanks

**Comment by goat1000** [comment]
Version 2.24 now has a "keep_colour_order" option for using colours in their original order.
