### ISSUE TITLE
Semi circle donut

### ISSUE THREAD

**Issue by boussou** [goat1000/SVGGraph#8]
Hi,

I tried to create a **Semi circle donut** by subclassing SVGGraphDonutGraph.php.

like this: (borrowed from highcharts)
![screenshot30](https://cloud.githubusercontent.com/assets/2531688/19246908/e4ccf16c-8f28-11e6-95a0-d79793bef0e2.png)

Currenlty failed attempt.
Have you any hint to help me achieve this?

**Comment by goat1000** [comment]
I've already got some new graph types planned so I'll add a semi-circular donut graph to the list. I can't really give you any decent clues about how to make your own graph class because I wouldn't know what needs changing until I tried it.

In any case, here's an example of a donut graph that looks like a semi-donut graph because the bottom half is not visible:
```php
<?php
require_once 'SVGGraph.php';

$values = array(
  array('Opera', 3, '#8085e9',),
  array('Safari', 7, '#f7a35c',),
  array('Chrome', 27, '#90ed7d',),
  array('IE', 46, '#434348',),
  array('Firefox', 17, '#7cb5ec',),
  array(' ', 100, 'none',),
);

$settings = array(
  'stroke_width' => 1,
  'stroke_colour' => '#fff',
  'back_colour' => '#fff',
  'back_stroke_width' => 0,
  'inner_radius' => 0.55,
  'structure' => array(
    'key' => 0,
    'value' => 1,
    'colour' => 2,
  ),
  'sort' => false,
  'reverse' => true,
  'data_label_font_size' => 11,
  'data_label_font_weight' => 'bold',
  'data_label_back_colour' => '#000',
  'data_label_colour' => '#fff',
  'pad_left' => 5,
  'pad_right' => 5,
  'pad_top' => 5,
  'pad_bottom' => -185,
  'inner_text' => "Browser\nshares\n2015\n\n\n",
  'inner_text_font_size' => 20,
  'inner_text_font_weight' => 'normal',
  'inner_text_back_colour' => 'none',
  'inner_text_colour' => '#333',
  'tooltip_callback' => function($d, $k, $v) {
    return ($v < 100 ? "$v%" : NULL);
  },
);

$graph = new SVGGraph(400, 200, $settings);

$graph->Values($values);
$graph->Render('DonutGraph');
```

The important parts are setting the bottom padding a to a negative value, making the empty slice transparent with a colour of `"none"` and disabling its tooltip in the callback function.

**Comment by goat1000** [comment]
Version 2.24 now has a semi-donut graph.

**Comment by boussou** [comment]
Bravo - I'll try it this week ;-)
